### ISSUE TITLE
Create EC2 source

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/aws-source#5] opened 2022-01-11 12:40 UTC
I need to be able to link things to EC2 instances, for example in an ELB you get the following:

```yaml
targetHealthDescriptions:
  - healthCheckPort: '8080'
    target:
      id: i-096d30d179e897333
      port: 8080
    targetHealth:
      description: 'Health checks failed with these codes: [401]'
      reason: Target.ResponseCodeMismatch
      state: unhealthy
  - healthCheckPort: '8080'
    target:
      id: i-03b6987020616a2f1
      port: 8080
    targetHealth:
      description: Health checks failed
      reason: Target.FailedHealthChecks
      state: unhealthy
```

I should be able to query EC2 instances so that I can link apps all the way through

**Comment by DavidS-om** [comment] 2022-11-29 10:50
Duplicate of #16

**Closed by DavidS-om** 2022-11-29 10:50 UTC
